version: "3"
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./notebooks:/jupyter/notebooks
    ports:
      - 8050:8050 # for Dash
      - 8888:8888 # for Jupyterlab
